interface Event {
    idEvent: string;
    idSoccerXML: string | null;
    idAPIfootball: string | null;
    strEvent: string;
    strEventAlternate: string;
    strFilename: string;
    strSport: string;
    idLeague: string;
    strLeague: string;
    strSeason: string;
    strDescriptionEN: string;
    strHomeTeam: string;
    strAwayTeam: string;
    intHomeScore: string;
    intRound: string;
    intAwayScore: string;
    intSpectators: string | null;
    strOfficial: string | null;
    strTimestamp: string;
    dateEvent: string;
    dateEventLocal: string;
    strTime: string;
    strTimeLocal: string;
    strTVStation: string | null;
    idHomeTeam: string;
    idAwayTeam: string;
    intScore: string | null;
    intScoreVotes: string | null;
    strResult: string;
    idVenue: string | null;
    strVenue: string;
    strCountry: string;
    strCity: string;
    strPoster: string;
    strSquare: string;
    strFanart: string;
    strThumb: string;
    strBanner: string;
    strMap: string | null;
    strTweet1: string;
    strTweet2: string;
    strTweet3: string;
    strVideo: string;
    strStatus: string;
    strPostponed: string;
    strLocked: string;
}
