interface Team {
    idTeam: string;
    idSoccerXML: string | null;
    idAPIfootball: string | null;
    intLoved: string;
    strTeam: string;
    strTeamShort: string;
    strAlternate: string;
    intFormedYear: string;
    strSport: string;
    strLeague: string;
    idLeague: string;
    strLeague2: string;
    idLeague2: string;
    strLeague3: string;
    idLeague3: string;
    strLeague4: string;
    idLeague4: string;
    strLeague5: string;
    idLeague5: string;
    strLeague6: string | null;
    idLeague6: string | null;
    strLeague7: string | null;
    idLeague7: string | null;
    strDivision: string | null;
    strStadium: string;
    strKeywords: string;
    strRSS: string;
    strStadiumThumb: string;
    strStadiumDescription: string;
    strStadiumLocation: string;
    intStadiumCapacity: string;
    strWebsite: string;
    strFacebook: string;
    strTwitter: string;
    strInstagram: string;
    strDescriptionEN: string;
    strDescriptionDE?: string;
    strDescriptionFR?: string;
    strDescriptionCN?: string | null;
    strDescriptionIT?: string;
    strDescriptionJP?: string;
    strDescriptionRU?: string;
    strDescriptionES?: string;
    strDescriptionPT?: string;
    strDescriptionSE?: string | null;
    strDescriptionNL?: string | null;
    strDescriptionHU?: string | null;
    strDescriptionNO?: string;
    strDescriptionIL?: string | null;
    strDescriptionPL?: string | null;
    strKitColour1: string;
    strKitColour2: string;
    strKitColour3: string | null;
    strGender: string;
    strCountry: string;
    strTeamBadge: string;
    strTeamJersey: string;
    strTeamLogo: string;
    strTeamFanart1: string;
    strTeamFanart2: string;
    strTeamFanart3: string;
    strTeamFanart4: string;
    strTeamBanner: string;
    strYoutube: string;
    strLocked: string;
}
